"""add_token_purpose

Revision ID: 913ed6b0dfda
Revises: a1b0c0cfc97c
Create Date: 2026-06-16 05:02:10.999947

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "913ed6b0dfda"
down_revision: Union[str, Sequence[str], None] = "a1b0c0cfc97c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

purpose_enum = postgresql.ENUM(
    "EMAIL_VERIFICATION",
    "PASSWORD_RESET",
    "TWO_FACTOR_AUTH",
    "WITHDRAWAL_CONFIRMATION",
    name="otp_token_purpose",
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    purpose_enum.create(op.get_bind())

    op.add_column(
        "otp_tokens",
        sa.Column(
            "purpose",
            postgresql.ENUM(
                "EMAIL_VERIFICATION",
                "PASSWORD_RESET",
                "TWO_FACTOR_AUTH",
                "WITHDRAWAL_CONFIRMATION",
                name="otp_token_purpose",
            ),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("otp_tokens", "purpose")

    purpose_enum.drop(op.get_bind())
    # ### end Alembic commands ###
