"""Add KYC documents and account tiers

Revision ID: c6c51418ee4a
Revises: e3524d5621ad
Create Date: 2026-06-10 08:06:53.638277

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "c6c51418ee4a"
down_revision: Union[str, Sequence[str], None] = "e3524d5621ad"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE account_tier_enum AS ENUM ('TIER_1', 'TIER_2', 'TIER_3')")

    op.create_table(
        "kyc_documents",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("users_id", sa.UUID(), nullable=False),
        sa.Column("document_type", sa.String(length=50), nullable=False),
        sa.Column("file_url", sa.String(length=255), nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM("PENDING", "APPROVED", "REJECTED", name="kyc_status_enum"),
            nullable=False,
        ),
        sa.Column("rejection_reason", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("reviewed_by_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(["reviewed_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["users_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_kyc_documents_users_id"), "kyc_documents", ["users_id"], unique=False
    )
    op.add_column(
        "users",
        sa.Column(
            "tier",
            postgresql.ENUM("TIER_1", "TIER_2", "TIER_3", name="account_tier_enum"),
            server_default="TIER_1",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_kyc_documents_users_id"), table_name="kyc_documents")
    op.drop_table("kyc_documents")

    op.drop_column("users", "tier")

    op.execute("DROP TYPE IF EXISTS account_tier_enum CASCADE")
    op.execute("DROP TYPE IF EXISTS kyc_status_enum CASCADE")

    # ### end Alembic commands ###
